export const homepage = [
  {
    title: "Star Beings 3",
    artist: "Various Artist",
    releasedate: "February 2023",
    content: "Our first release for 2023, the 3rd edition of the “Star Beings'' series is finally ready to lift off!",
    icon: "charm:rocket",
    image:"starbeings.jpg",    
    url: "https://pleiadianrecords.bandcamp.com/album/star-beings-3",
  },
  {
    title: "Ruminative",
    artist: "Frantic Noise",
    releasedate: "November 2022",
    content: "Frantic Noise presents to us once again an auditory serenade aimed at inspiring the next levels of human consciousness. ",
    icon: "ph:code-bold",    
    image:"ruminative.jpg",    
    url: "https://pleiadianrecords.bandcamp.com/album/ruminative",
  },
  {
    title: "Kintsugi",
    artist: "Zombie Scream",
    releasedate: "September 2022",
    content: "Fragments of sonic creations skillfully pieced together in a golden outline with the swiftness and grace that only Zombie Scream can present.",
    icon: "charm:plant-pot",
    image:"kintsugi.jpg",
    url: "https://pleiadianrecords.bandcamp.com/album/kintsugi",
  },
  {
    title: "Maa Asi",
    artist: "Keluk",
    releasedate: "August 2022",
    content: "KELUK aka Karl Ölluk coming out of Estonia, brings us four deep psychoactive melodies that we are sure to take you into an unforgettable journey.",
    icon: "charm:rocket",
    image:"maaasi.jpg",    
    url: "https://pleiadianrecords.bandcamp.com/album/maa-asi",
  },
  {
    title: "Organic",
    artist: "Zombie Scream",
    releasedate: "May 2022",
    content: "Immerse yourself into the mind of Aaron Lopez and navigate a tasty psychedelic tune at 145 Bpm!",
    icon: "charm:plant-pot",
    image:"organic.jpg",
    url: "https://pleiadianrecords.bandcamp.com/track/organic",
  },
  {
    title: "Rocketship",
    artist: "Frantic Noise",
    releasedate: "November 2021",
    content: "Frantic Noise brings us once again an EP filled with a superb collection of succulent psychedelic sounds featuring four tracks that will take you through ethereal space",
    icon: "ph:code-bold",    
    image:"rocketship.jpg",    
    url: "https://pleiadianrecords.bandcamp.com/album/rocketship",
  },
  {
    title: "Twenty Two",
    artist: "K Freq",
    releasedate: "October 2021",
    content: "Once again Pleiadian Records brings you a mind bending release, this time we venture in to a 4 track journey through psychedelic spacetime.",
    icon: "charm:plant-pot",
    image:"twentytwo.jpg",
    url: "https://pleiadianrecords.bandcamp.com/album/twenty-two",
  },
  {
    title: "Havoc 2",
    artist: "Frantic Noise",
    releasedate: "April 2021",
    content: "Enjoy the outstanding second adventure of “Havoc” by Frantic Noise, feat. stunning collaboration tracks with Virtuanoise, Divine Stones and Mooncake.",
    icon: "charm:plant-pot",
    image:"havoc2.jpg",
    url: "https://pleiadianrecords.bandcamp.com/album/havoc-vol-2",
  },
];
